services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_INITDB_ROOT_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_INITDB_ROOT_PASSWORD}'
    volumes:
      - './data:/data/db'
  mongoui:
    image: mongo-express
    container_name: mongoui
    restart: unless-stopped
    ports:
      - 5006:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: '${ME_CONFIG_MONGODB_ADMINUSERNAME}'
      ME_CONFIG_MONGODB_ADMINPASSWORD: '${ME_CONFIG_MONGODB_ADMINPASSWORD}'
      ME_CONFIG_MONGODB_URL: 'mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/'
