services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: EasyBooks
      MONGO_INITDB_ROOT_PASSWORD: UvNHKf8BSeBkMjRE
    volumes:
      - './data:/data/db'
  mongoui:
    image: mongo-express
    container_name: mongoui
    restart: unless-stopped
    ports:
      - 5006:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: EasyBooks
      ME_CONFIG_MONGODB_ADMINPASSWORD: PXwjrCnPnqYSk858
      ME_CONFIG_MONGODB_URL: mongodb://EasyBooks:UvNHKf8BSeBkMjRE@mongo:27017/
